# Alacritty Configuration File (TOML format)

[font]
size = 10

[font.normal]
family = "Martian Mono Nerd Font"
style = "Regular"

[font.bold]
family = "Martian Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Martian Mono Nerd Font"
style = "Italic"

[env]
TERM = "xterm-256color"

[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[colors.cursor]
text = "0x1e1e2e"
cursor = "0xf38ba8"

[colors.normal]
black = "0x45475a"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xcba6f7"
cyan = "0x94e2d5"
white = "0xcdd6f4"

[colors.bright]
black = "0x585b70"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xcba6f7"
cyan = "0x94e2d5"
white = "0xffffff"

[window]
dynamic_padding = true
decorations = "full"
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ClearHistory"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

